
CREATE TABLE M_SCENARIO
(
	_ID INTEGER NOT NULL,
	SCENARIO_NO INTEGER NOT NULL,
	SEQ_NO INTEGER NOT NULL,
	SCENE_TYPE INTEGER NOT NULL,
	SCENE_ID INTEGER NOT NULL,
	SCENARIO_TITLE TEXT,
	PRIMARY KEY (_ID)
);
