
CREATE TABLE M_SCENARIO
(
	_ID INTEGER NOT NULL,
	SCENARIO_NO INTEGER NOT NULL,
	SEQ_NO INTEGER NOT NULL,
	SCENE_TYPE INTEGER NOT NULL,
	SCENE_ID INTEGER NOT NULL,
	SCENARIO_TITLE TEXT,
	PRIMARY KEY (_ID)
);

CREATE TABLE M_ACTOR
(
	_ID INTEGER NOT NULL,
	NAME TEXT,
	IMG_RES_ID INTEGER,
	PRIMARY KEY (_ID)
);


CREATE TABLE T_ACTOR_STATUS
(
	_ID INTEGER NOT NULL,
	LEVEL INTEGER,
	EXP INTEGER,
	ATTACK_POINT INTEGER,
	DEFENCE_POINT INTEGER,
	HIT_POINT INTEGER,
	MAGIC_POINT INTEGER,
	MOVE_POINT INTEGER,
	ATTACK_RANGE INTEGER,
	FOREIGN KEY (_ID)
	REFERENCES M_ACTOR (_ID)
);

CREATE TABLE T_SAVE_DATA
(
	_ID INTEGER NOT NULL,
	SCENARIO_NO INTEGER,
	SEQ_NO INTEGER,
	PRIMARY KEY (_ID)
);
